/**
 * Agent Host Protocol (AHP) — type definitions and reducers.
 *
 * Vendored from Microsoft's open-source [Agent Host Protocol](https://github.com/microsoft/agent-host-protocol)
 * and built via a prebuild transform step.
 *
 * The vendored source lives under `src/vendor/ahp/`. This file re-exports the
 * canonical shapes and the pure reducer functions that fold AHP actions into
 * derived state.
 *
 * @module agent-host-protocol
 */

// ─── State shapes ───────────────────────────────────────────────

export type {
  URI,
  StringOrMarkdown,
  Icon,
  RootState,
  RootConfigState,
  AgentInfo,
  ProtectedResourceMetadata,
  ProjectInfo,
  SessionModelInfo,
  ModelSelection,
  AgentSelection,
  SessionState,
  SessionSummary,
  SessionConfigState,
  SessionConfigPropertySchema,
  SessionConfigSchema,
  SessionInputOption,
  SessionInputTextQuestion,
  SessionInputNumberQuestion,
  SessionInputBooleanQuestion,
  SessionInputSingleSelectQuestion,
  SessionInputMultiSelectQuestion,
  UserMessage,
  MessageAttachment,
  MessageAttachmentBase,
  ResponsePart,
  ToolCallResponsePart,
  ToolCallState,
  ToolCallResult,
  ToolResultContent,
  ToolDefinition,
  ToolAnnotations,
  SessionActiveClient,
  SessionCustomization,
  CustomizationRef,
  CustomizationAgentRef,
  SessionInputRequest,
  SessionInputAnswer,
  SessionInputAnswerValue,
  SessionInputQuestion,
  SessionInputAnswered,
  SessionInputSkipped,
  SessionInputTextAnswerValue,
  SessionInputNumberAnswerValue,
  SessionInputBooleanAnswerValue,
  SessionInputSelectedAnswerValue,
  SessionInputSelectedManyAnswerValue,
  PendingMessage,
  Snapshot,
  TerminalState,
  TerminalContentPart,
  TerminalUnclassifiedPart,
  TerminalCommandPart,
  ChangesetState,
  ChangesetSummary,
  ConfigPropertySchema,
  ConfigSchema,
  TextPosition,
  TextRange,
  TextSelection,
  ContentRef,
  FileEdit,
  UsageInfo,
  ErrorInfo,
  TelemetryCapabilities,
} from "./vendor/ahp/state.js";

// ─── Enum types ─────────────────────────────────────────────────

export type {
  PolicyState,
  SessionLifecycle,
  SessionStatus,
  PendingMessageKind,
  SessionInputResponseKind,
  SessionInputQuestionKind,
  SessionInputAnswerState,
  SessionInputAnswerValueKind,
  TurnState,
  MessageAttachmentKind,
  ResponsePartKind,
  ToolCallStatus,
  ToolCallConfirmationReason,
  ToolCallCancellationReason,
  ConfirmationOptionKind,
  ToolResultContentType,
  CustomizationStatus,
  TerminalClaimKind,
  ChangesetStatus,
  ChangesetOperationScope,
} from "./vendor/ahp/state.js";

// ─── Action types ───────────────────────────────────────────────

export type {
  ActionEnvelope,
  ActionOrigin,
  ActionType,
  StateAction,
  // Root actions
  RootAgentsChangedAction,
  RootActiveSessionsChangedAction,
  RootTerminalsChangedAction,
  RootConfigChangedAction,
  // Session actions
  SessionReadyAction,
  SessionCreationFailedAction,
  SessionTurnStartedAction,
  SessionDeltaAction,
  SessionResponsePartAction,
  SessionToolCallStartAction,
  SessionToolCallDeltaAction,
  SessionToolCallReadyAction,
  SessionToolCallApprovedAction,
  SessionToolCallDeniedAction,
  SessionToolCallCompleteAction,
  SessionToolCallResultConfirmedAction,
  SessionToolCallContentChangedAction,
  SessionTurnCompleteAction,
  SessionTurnCancelledAction,
  SessionErrorAction,
  SessionTitleChangedAction,
  SessionUsageAction,
  SessionReasoningAction,
  SessionModelChangedAction,
  SessionAgentChangedAction,
  SessionServerToolsChangedAction,
  SessionActiveClientChangedAction,
  SessionActiveClientToolsChangedAction,
  SessionPendingMessageSetAction,
  SessionPendingMessageRemovedAction,
  SessionQueuedMessagesReorderedAction,
  SessionInputRequestedAction,
  SessionInputAnswerChangedAction,
  SessionInputCompletedAction,
  SessionCustomizationsChangedAction,
  SessionCustomizationToggledAction,
  SessionCustomizationUpdatedAction,
  SessionTruncatedAction,
  SessionIsReadChangedAction,
  SessionIsArchivedChangedAction,
  SessionActivityChangedAction,
  SessionChangesetsChangedAction,
  SessionConfigChangedAction,
  SessionMetaChangedAction,
  // Terminal actions
  TerminalDataAction,
  TerminalInputAction,
  TerminalResizedAction,
  TerminalClaimedAction,
  TerminalTitleChangedAction,
  TerminalCwdChangedAction,
  TerminalExitedAction,
  TerminalClearedAction,
  TerminalCommandDetectionAvailableAction,
  TerminalCommandExecutedAction,
  TerminalCommandFinishedAction,
  // Changeset actions
  ChangesetStatusChangedAction,
  ChangesetFileSetAction,
  ChangesetFileRemovedAction,
  ChangesetOperationsChangedAction,
  ChangesetClearedAction,
} from "./vendor/ahp/actions.js";

// ─── Command types ──────────────────────────────────────────────

export type {
  BaseParams,
  InitializeParams,
  InitializeResult,
  PingParams,
  ReconnectParams,
  ReconnectResult,
  SubscribeParams,
  SubscribeResult,
  UnsubscribeParams,
  DispatchActionParams,
  ResourceReadParams,
  ResourceReadResult,
  ResourceWriteParams,
  ResourceWriteResult,
  ResourceListParams,
  DirectoryEntry,
  ResourceListResult,
  ResourceCopyParams,
  ResourceCopyResult,
  ResourceDeleteParams,
  ResourceDeleteResult,
  ResourceRequestParams,
  ResourceRequestResult,
  ResourceMoveParams,
  ResourceMoveResult,
  AuthenticateParams,
  AuthenticateResult,
  ListSessionsParams,
  ListSessionsResult,
  ResolveSessionConfigParams,
  ResolveSessionConfigResult,
  SessionConfigValueItem,
  SessionConfigCompletionsParams,
  SessionConfigCompletionsResult,
  CreateSessionParams,
  SessionForkSource,
  DisposeSessionParams,
  FetchTurnsParams,
  FetchTurnsResult,
  CompletionsParams,
  CompletionItem,
  CompletionsResult,
  CreateTerminalParams,
  DisposeTerminalParams,
  InvokeChangesetOperationParams,
  ChangesetOperationTarget,
  ChangesetOperationFollowUp,
} from "./vendor/ahp/commands.js";

// ─── Enum types (commands) ──────────────────────────────────────

export type {
  ReconnectResultType,
  ContentEncoding,
  CompletionItemKind,
  ChangesetOperationTargetKind,
} from "./vendor/ahp/commands.js";

// ─── Notifications ──────────────────────────────────────────────

export type {
  AuthRequiredReason,
  AuthRequiredParams,
  SessionAddedParams,
  SessionRemovedParams,
  SessionSummaryChangedParams,
  OtlpExportLogsParams,
  OtlpExportTracesParams,
  OtlpExportMetricsParams,
} from "./vendor/ahp/notifications.js";

// ─── Messages ───────────────────────────────────────────────────

export type {
  JsonRpcRequest,
  JsonRpcSuccessResponse,
  JsonRpcErrorResponse,
  AhpErrorResponse,
  CommandMap,
  ServerCommandMap,
  ClientNotificationMap,
  ServerNotificationMap,
  JsonRpcResponse,
  AhpRequest,
  AhpServerRequest,
  AhpSuccessResponse,
  AhpResponse,
  AhpServerSuccessResponse,
  AhpServerResponse,
  AhpClientNotification,
  AhpServerNotification,
  AhpNotification,
  ProtocolMessage,
} from "./vendor/ahp/messages.js";

// ─── Reducer functions ──────────────────────────────────────────

export {
  rootReducer,
  sessionReducer,
  terminalReducer,
  changesetReducer,
  softAssertNever,
  isClientDispatchable,
} from "./vendor/ahp/reducers.js";
